config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^tournaments/$', TemplateView.as_view(template_name='ladder/tournaments.html'), name='tournaments'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('fbw.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('ladder.urls', namespace='ladder'))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

fbw/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

ladder/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^submit/', login_required(views.MatchFormView.as_view()), name='submit'),
    url(r'^match/$', login_required(views.MatchListView.as_view()), name='match-list'),
    url(r'^match/unconfirmed$', login_required(views.UnconfirmedMatchesView.as_view()), name='unconfirmed-matches'),
    url(r'^match/parse$', views.parse_replay, name='replay-parse'),
    url(r'^match/(?P<pk>\d+)/$', login_required(views.MatchDetailView.as_view()), name='match-detail'),
    url(r'^match/(?P<pk>\d+)/edit$', login_required(views.MatchEditView.as_view()), name='match-edit'),
    url(r'^match/(?P<pk>\d+)/delete$', login_required(views.MatchDeleteView.as_view()), name='match-delete'),
    url(r'^match/(?P<pk>\d+)/confirm$', login_required(views.confirm_match), name='match-confirm'),
    url(r'^match/(?P<pk>\d+)/report$', login_required(views.MatchReportView.as_view()), name='match-report'),
    url(r'^players$', views.PlayerListView.as_view(), name='player-list'),
]

fbw/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from ladder.models import Match


@python_2_unicode_compatible
class User(AbstractUser):
    RACE_CHOICES = (
        ('Z', 'Zerg'),
        ('T', 'Terran'),
        ('P', 'Protoss'),
        ('R', 'Random'),
    )

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    battlenet = models.CharField(max_length=100, unique=True, null=True, blank=True)
    iccup = models.CharField(max_length=100, unique=True, null=True, blank=True)
    race = models.CharField(max_length=1, choices=RACE_CHOICES)
    rating = models.IntegerField(default=1200)
    shield_battery = models.CharField(max_length=100, unique=True, null=True, blank=True)

    class Meta:
        ordering = ('username',)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    @property
    def games_played(self):
        return Match.objects.filter(Q(winner=self) | Q(loser=self)).count()
    

    @property
    def winrates(self):
        wins = Match.objects.filter(winner=self)
        losses = Match.objects.filter(loser=self)

        matchups = {
            'ZvT_wins': 0,
            'ZvT_games': 0,
            'ZvP_wins': 0,
            'ZvP_games': 0,
            'ZvZ_wins': 0,
            'ZvZ_games': 0,
            'TvZ_wins': 0,
            'TvZ_games': 0,
            'TvT_wins': 0,
            'TvT_games': 0,
            'TvP_wins': 0,
            'TvP_games': 0,
            'PvZ_wins': 0,
            'PvZ_games': 0,
            'PvP_wins': 0,
            'PvP_games': 0,
            'PvT_wins': 0,
            'PvT_games': 0,
        }

        # god forgive me for what i'm about to do
        for match in wins:
            if match.winner_race == 'Z':
                if match.loser_race == 'T':
                    matchups['ZvT_games'] += 1
                    matchups['ZvT_wins'] += 1
                if match.loser_race == 'P':
                    matchups['ZvP_games'] += 1
                    matchups['ZvP_wins'] += 1
                if match.loser_race == 'Z':
                    matchups['ZvZ_games'] += 1
                    matchups['ZvZ_wins'] += 1
            if match.winner_race == 'P':
                if match.loser_race == 'T':
                    matchups['PvT_games'] += 1
                    matchups['PvT_wins'] += 1
                if match.loser_race == 'P':
                    matchups['PvP_games'] += 1
                    matchups['PvP_wins'] += 1
                if match.loser_race == 'Z':
                    matchups['PvZ_games'] += 1
                    matchups['PvZ_wins'] += 1
            if match.winner_race == 'T':
                if match.loser_race == 'T':
                    matchups['TvT_games'] += 1
                    matchups['TvT_wins'] += 1
                if match.loser_race == 'P':
                    matchups['TvP_games'] += 1
                    matchups['TvP_wins'] += 1
                if match.loser_race == 'Z':
                    matchups['TvZ_games'] += 1
                    matchups['TvZ_wins'] += 1

        for match in losses:
            if match.loser_race == 'Z':
                if match.winner_race == 'T':
                    matchups['ZvT_games'] += 1
                if match.winner_race == 'P':
                    matchups['ZvP_games'] += 1
                if match.winner_race == 'Z':
                    matchups['ZvZ_games'] += 1
            if match.loser_race == 'P':
                if match.winner_race == 'T':
                    matchups['PvT_games'] += 1
                if match.winner_race == 'P':
                    matchups['PvP_games'] += 1
                if match.winner_race == 'Z':
                    matchups['PvZ_games'] += 1
            if match.loser_race == 'T':
                if match.winner_race == 'T':
                    matchups['TvT_games'] += 1
                if match.winner_race == 'P':
                    matchups['TvP_games'] += 1
                if match.winner_race == 'Z':
                    matchups['TvZ_games'] += 1

        return {
            'ZvT': "{0:.0f}%".format(matchups['ZvT_wins'] / matchups['ZvT_games'] * 100) if matchups['ZvT_games'] > 0 else "",
            'ZvP': "{0:.0f}%".format(matchups['ZvP_wins'] / matchups['ZvP_games'] * 100) if matchups['ZvP_games'] > 0 else "",
            'ZvZ': "{0:.0f}%".format(matchups['ZvZ_wins'] / matchups['ZvZ_games'] * 100) if matchups['ZvZ_games'] > 0 else "",
            'TvT': "{0:.0f}%".format(matchups['TvT_wins'] / matchups['TvT_games'] * 100) if matchups['TvT_games'] > 0 else "",
            'TvP': "{0:.0f}%".format(matchups['TvP_wins'] / matchups['TvP_games'] * 100) if matchups['TvP_games'] > 0 else "",
            'TvZ': "{0:.0f}%".format(matchups['TvZ_wins'] / matchups['TvZ_games'] * 100) if matchups['TvZ_games'] > 0 else "",
            'PvT': "{0:.0f}%".format(matchups['PvT_wins'] / matchups['PvT_games'] * 100) if matchups['PvT_games'] > 0 else "",
            'PvP': "{0:.0f}%".format(matchups['PvP_wins'] / matchups['PvP_games'] * 100) if matchups['PvP_games'] > 0 else "",
            'PvZ': "{0:.0f}%".format(matchups['PvZ_wins'] / matchups['PvZ_games'] * 100) if matchups['PvZ_games'] > 0 else "",
        }

    @property
    def unconfirmed_matches(self):
        unconfirmed_wins = Match.objects.filter(Q(winner=self) & Q(winner_confirmed=False)).count()
        unconfirmed_losses = Match.objects.filter(Q(loser=self) & Q(loser_confirmed=False)).count()
        return unconfirmed_wins + unconfirmed_losses

ladder/forms.py
from django import forms

from .models import Match, Report

class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        exclude = ('replay', 'date', 'winner_confirmed', 'loser_confirmed', 'calculated', 'winner_rating_change', 'loser_rating_change')


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('report_type', 'description')

    def __init__(self, *args, **kwargs):
        self.match_id = kwargs.pop('match_id', None)
        self.reporter = kwargs.pop('reporter')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        model = super().save(commit=False)
        model.match = Match.objects.get(pk=self.match_id)
        model.reporter = self.reporter

        if commit:
            model.save()
        return model


class MatchReplayForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ('replay',)

ladder/views.py
import json
import os
import subprocess
import tempfile

from django.conf import settings
from django.core.files.uploadhandler import TemporaryFileUploadHandler
from django.db.models import Q
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .models import Match
from .forms import MatchForm, ReportForm, MatchReplayForm
from fbw.users.models import User


# Create your views here.
class MatchFormView(generic.FormView):
    form_class = MatchReplayForm
    template_name = 'ladder/submit.html'

    def get_success_url(self):
        return self.object.get_absolute_url() + 'edit'

    def form_valid(self, form):
        self.object = form.save()
        if self.request.user == self.object.winner:
            self.object.winner_confirmed = True
        elif self.request.user == self.object.loser:
            self.object.loser_confirmed = True
        self.object.save()
        return super().form_valid(form)


class MatchReportView(generic.FormView):
    template_name = 'ladder/report_match.html'
    form_class = ReportForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['match_id'] = self.kwargs['pk']
        kwargs['reporter'] = self.request.user
        return kwargs

    def get_success_url(self):
        return self.object.match.get_absolute_url()

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_context_data(self):
        context = super().get_context_data()
        context['match_id'] = self.kwargs['pk']
        return context


class MatchDetailView(generic.DetailView):
    model = Match
    template_name = 'ladder/match_detail.html'


class MatchEditView(generic.UpdateView):
    model = Match
    form_class = MatchForm
    template_name = 'ladder/match_edit.html'


class UnconfirmedMatchesView(generic.ListView):
    model = Match
    template_name = 'ladder/unconfirmed_matches.html'
    context_object_name = 'matches'
    paginate_by = 10

    def get_queryset(self):
        unconfirmed_wins = Match.objects.filter(Q(winner=self.request.user) & Q(winner_confirmed=False))
        unconfirmed_losses = Match.objects.filter(Q(loser=self.request.user) & Q(loser_confirmed=False))
        return unconfirmed_wins | unconfirmed_losses

class PlayerListView(generic.ListView):
    model = User
    template_name = 'ladder/player_list.html'
    context_object_name = 'players'
    ordering = '-rating'
    paginate_by = 15


class MatchListView(generic.ListView):
    model = Match
    template_name = 'ladder/match_list.html'
    context_object_name = 'matches'
    paginate_by = 15
    queryset = Match.objects.all().prefetch_related('winner', 'loser')


class MatchDeleteView(generic.DeleteView):
    model = Match
    success_url = reverse_lazy('ladder:match-list')


class IndexView(generic.ListView):
    model = User
    template_name = 'ladder/match_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['player_list'] = User.objects.all().order_by('-rating')[:10]
        context['recent_matches'] = Match.objects.all().prefetch_related('winner', 'loser')[:10]
        return context


def confirm_match(request, pk):
    match = Match.objects.get(pk=pk)
    if request.user == match.winner:
        match.winner_confirmed = True
        match.save()
        return redirect(match)
    elif request.user == match.loser:
        match.loser_confirmed = True
        match.save()
        return redirect(match)
    else:
        return HttpResponseForbidden()


@csrf_exempt
def parse_replay(request):
    request.upload_handlers = [TemporaryFileUploadHandler(request)]
    replay = request.FILES["replay"].temporary_file_path()
    screp_path = os.path.join(os.path.dirname(__file__)) + '/screp'
    parsed = subprocess.run([screp_path, "-map", replay], stdout=subprocess.PIPE).stdout.decode('utf-8')
    return JsonResponse(json.loads(parsed))

ladder/templates/ladder/match_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row text-center">
        <div class="col-sm-12">
        <h1 style="margin-top: 20px; margin-bottom: 20px;">Match Details</h1>


        {% if object.winner.username and object.loser.username %}
            {% if object.calculated %}

                <h3>
                    <strong>
                        <a href="{% url 'users:detail' object.winner.username %}">{{ object.winner.username }}</a> 
                        <small class="winner-name">(+{{ object.winner_rating_change }})</small> 
                        - 
                        <a href="{% url 'users:detail' object.loser.username %}">{{ object.loser.username }}</a> 
                        <small class="loser-name">(-{{ object.loser_rating_change }})</small>
                    </strong>
                </h3>
            {% else %}

                <h3><strong><a href="{% url 'users:detail' object.winner.username %}">{{ object.winner.username }}</a> - <a href="{% url 'users:detail' object.loser.username %}">{{ object.loser.username }}</a></strong></h3>
                {% if request.user == object.winner %}
                    {% if not object.winner_confirmed %}
                        <a href="{% url 'ladder:match-confirm' object.id %}">Confirm Match</a>
                    {% else %}
                        <p>You have confirmed the match, but your opponent has not. Please remind them to confirm the results.</p>
                    {% endif %}
                {% elif request.user == object.loser %}
                    {% if not object.loser_confirmed %}
                        <a href="{% url 'ladder:match-confirm' object.id %}">Confirm Match</a>
                    {% else %}
                        <p>You have confirmed the match, but your opponent has not. Please remind them to confirm the results.</p>
                    {% endif %}
                {% else %}
                    <p>This match has not yet been confirmed by both players.</p>
                {% endif %}
            {% endif %}
        {% else %}
            <h3>The match details are pending.</h3>
        {% endif %}
            <p><strong>Date:</strong> {{ object.date }}</p>
            <p><strong>Map:</strong> {{ object.match_map }}</p>
            <p>
                <a href="{{ object.replay.url}}" download><button class="btn btn-primary">Download Replay</button></a>
                <a href="{% url 'ladder:match-report' object.id %}"><button class="btn btn-danger">Report Match</button></a>
            </p>
            <p>
                <h3>Admin Actions</h3>
                {% if request.user.is_superuser %}
                    <p><a href="{% url 'ladder:match-edit' object.id %}"><button class="btn btn-primary">Edit Match</button></a></p>
                    <form method="POST" action="{% url 'ladder:match-delete' object.id %}">{% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete Match</button>
                    </form>
                {% endif %}
            </p>
    </div>
{% endblock %}

ladder/templates/ladder/match_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Confirm Match Details</h1>
    <form method="POST" action="{% url 'ladder:match-edit' object.pk %}">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

ladder/templates/ladder/match_index.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-6">
            {% if player_list %}
                <h2>Top Players</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <td>Player</td>
                            <td>Rating</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for player in player_list %}
                            <tr>
                                <td><a href="{% url 'users:detail' player.username %}">{{ player.username }}</a></td>
                                <td>{{ player.rating }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h2>Waiting for Players</h2>
            {% endif %}
        </div>
        <div class="col-sm-6">
            {% if recent_matches %}
                <h2>Recent Matches</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <td>Players</td>
                            <td>Date</td>
                            <td>Map</td>
                        </tr>
                    <tbody>
                        {% for match in recent_matches %}
                            <tr>
                                <td><a href="{% url 'ladder:match-detail' match.id %}">{{ match.winner }} vs {{ match.loser }}</a></td>
                                <td>{{ match.date }}</td>
                                <td>{{ match.match_map }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h2>Waiting for Matches</h2>
            {% endif %}
        </div>
    </div>
{% endblock %}

ladder/templates/ladder/match_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Recent Matches</h1>
    <table class="table">
        <thead>
            <tr>
                <td>Date</td>
                <td>Players</td>
                <td>Map</td>
                <td>Direct Download</td>
            </tr>
        </thead>
        <tbody>
            {% for match in matches %}
                <tr>
                    <td>{{ match.date }}</td>
                    <td><a href="{% url 'ladder:match-detail' match.id %}">{{ match.winner.username }} vs {{ match.loser.username }}</a></td>
                    <td>{{ match.match_map }}</td>
                    <td><a href="{{ match.replay.url }}" download>{{ match.replay.name }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'ladder:match-list' %}?page={{page_obj.previous_page_number}}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'ladder:match-list' %}?page={{page_obj.next_page_number}}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

ladder/templates/ladder/player_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Rankings</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Rank</td>
                <td>Rating</td>
                <td>Player</td>
                <td>Race</td>
                <td>Games Played</td>
            </tr>
        </thead>
        <tbody>
            {% for player in players %}
                <tr>
                    <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                    <td>{{ player.rating }}</td>
                    <td><a href="{% url 'users:detail' player.username %}">{{ player.username }}</a></td>
		    <td>{{ player.get_race_display }}</td>
		    <td>{{ player.games_played }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'ladder:player-list' %}?page={{page_obj.previous_page_number}}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'ladder:player-list' %}?page={{page_obj.next_page_number}}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

ladder/templates/ladder/report_match.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="text-center">Report Match</h1>
    <form method="POST" action="{% url 'ladder:match-report' match_id %}" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

ladder/templates/ladder/submit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="text-center">Submit Match</h1>
    <form method="POST" action="{% url 'ladder:submit' %}" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

ladder/templates/ladder/tournaments.html
{% extends 'base.html' %}

{% block content %}
    <h1>Foreign Brood War Ladder Season 1 Tournament</h1>

    <p>It is our pleasure to introduce the FBWL Season 1 Finale Tournament on July 29th, 2017. The ladder has been a tremendous success, with hundreds of games being played in the first month, and numerous new members of our community taking part. To cap off the first season, we are launching a four round, Top 16 tournament featuring the best players in the FBW Discord community. With casters from within our community and viewership hopefully across many communities, we think this tournament will be a fun, competitive event</p>

    <p>The prize pool is TBD (and we encourage any of you who would like to donate to the priz epool to do so) and <b>all</b> qualified players will receive some portion of the prizes.</p>

    <p>Currently, the great <b>Schamtoo</b> has agreed to cast the tournament, and we would be thrilled to take applicants from other members who want to throw their hat in the casting ring.</p>

    <p>To outline:</p>
    <ul>
        <li><b>When:</b> July 29th, 2017 (time TBD)</li>
        <li><b>Where:</b> Battle.net, patch 1.18</li>
        <li><b>Who plays: </b>The top 16 ranked players on the FBW Ladder</li>
        <li><b>Who casts: </b>Schamtoo and more guests TBD.</li>
        <li><b>How much: </b>The prize pool is TBD and you are more than welcome to contribute to it.</li>
    </ul>

    <h2>About 'Foreign' and 'Korean'</h2>
    <p>It's been a hot topic of discussion recently about what constitutes foreign and Korean, and how these tournaments should be segregated as to best grow the community, provide good viewing experiences, and be inclusive. It's not an easy question to answer. The following is the current stance of FBW Discord Ladder:</p>
    <p>As a foreign community-driven event, we will be barring entry of professional and semi-professional players (players who have previously or currently attended prestiguous tournaments in Korea such as but not limited to: OSL, MSL, ASL, and other Kespa/Afreeca sponsored events. We have taken this stance as our discord as well as the foreign community at large has an influx of new players, players transitioning from StarCraft 2, and players who are just coming back after a long hiatus. Our aim with this ladder, although competitive in nature, is also about welcoming and encouraging participation among said players in a friendly environment where they have the chance to play likeminded people.</p>

    <p><b>We look forward to seeing you there!</b></p>
{% endblock %}

ladder/templates/ladder/unconfirmed_matches.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Unconfirmed Matches</h1>
    {% if matches %}
        <table class="table">
            <thead>
                <tr>
                    <td>Date</td>
                    <td>Players</td>
                    <td>Map</td>
                    <td>Direct Download</td>
                </tr>
            </thead>
            <tbody>
                {% for match in matches %}
                    <tr>
                        <td>{{ match.date }}</td>
                        <td><a href="{% url 'ladder:match-detail' match.id %}">{{ match.winner.username }} vs {{ match.loser.username }}</a></td>
                        <td>{{ match.match_map }}</td>
                        <td><a href="{{ match.replay.url }}" download>{{ match.replay.name }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="{% url 'ladder:match-list' %}?page={{page_obj.previous_page_number}}">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="{% url 'ladder:match-list' %}?page={{page_obj.next_page_number}}">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
                {% endif %}
            </ul>
        {% endif %}
    {% else %}
        <p class="text-center">You have no unconfirmed matches at this time.</p>
    {% endif %}
{% endblock %}