config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^tournaments/$', TemplateView.as_view(template_name='ladder/tournaments.html'), name='tournaments'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('fbw.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('ladder.urls', namespace='ladder'))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

fbw/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

ladder/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^submit/', login_required(views.MatchFormView.as_view()), name='submit'),
    url(r'^match/$', login_required(views.MatchListView.as_view()), name='match-list'),
    url(r'^match/unconfirmed$', login_required(views.UnconfirmedMatchesView.as_view()), name='unconfirmed-matches'),
    url(r'^match/parse$', views.parse_replay, name='replay-parse'),
    url(r'^match/(?P<pk>\d+)/$', login_required(views.MatchDetailView.as_view()), name='match-detail'),
    url(r'^match/(?P<pk>\d+)/edit$', login_required(views.MatchEditView.as_view()), name='match-edit'),
    url(r'^match/(?P<pk>\d+)/delete$', login_required(views.MatchDeleteView.as_view()), name='match-delete'),
    url(r'^match/(?P<pk>\d+)/confirm$', login_required(views.confirm_match), name='match-confirm'),
    url(r'^match/(?P<pk>\d+)/report$', login_required(views.MatchReportView.as_view()), name='match-report'),
    url(r'^players$', views.PlayerListView.as_view(), name='player-list'),
]

fbw/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from ladder.models import Match


@python_2_unicode_compatible
class User(AbstractUser):
    RACE_CHOICES = (
        ('Z', 'Zerg'),
        ('T', 'Terran'),
        ('P', 'Protoss'),
        ('R', 'Random'),
    )

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    battlenet = models.CharField(max_length=100, unique=True, null=True, blank=True)
    iccup = models.CharField(max_length=100, unique=True, null=True, blank=True)
    race = models.CharField(max_length=1, choices=RACE_CHOICES)
    rating = models.IntegerField(default=1200)
    shield_battery = models.CharField(max_length=100, unique=True, null=True, blank=True)

    class Meta:
        ordering = ('username',)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    @property
    def games_played(self):
        return Match.objects.filter(Q(winner=self) | Q(loser=self)).count()
    

    @property
    def winrates(self):
        wins = Match.objects.filter(winner=self)
        losses = Match.objects.filter(loser=self)

        matchups = {
            'ZvT_wins': 0,
            'ZvT_games': 0,
            'ZvP_wins': 0,
            'ZvP_games': 0,
            'ZvZ_wins': 0,
            'ZvZ_games': 0,
            'TvZ_wins': 0,
            'TvZ_games': 0,
            'TvT_wins': 0,
            'TvT_games': 0,
            'TvP_wins': 0,
            'TvP_games': 0,
            'PvZ_wins': 0,
            'PvZ_games': 0,
            'PvP_wins': 0,
            'PvP_games': 0,
            'PvT_wins': 0,
            'PvT_games': 0,
        }

        # god forgive me for what i'm about to do
        for match in wins:
            if match.winner_race == 'Z':
                if match.loser_race == 'T':
                    matchups['ZvT_games'] += 1
                    matchups['ZvT_wins'] += 1
                if match.loser_race == 'P':
                    matchups['ZvP_games'] += 1
                    matchups['ZvP_wins'] += 1
                if match.loser_race == 'Z':
                    matchups['ZvZ_games'] += 1
                    matchups['ZvZ_wins'] += 1
            if match.winner_race == 'P':
                if match.loser_race == 'T':
                    matchups['PvT_games'] += 1
                    matchups['PvT_wins'] += 1
                if match.loser_race == 'P':
                    matchups['PvP_games'] += 1
                    matchups['PvP_wins'] += 1
                if match.loser_race == 'Z':
                    matchups['PvZ_games'] += 1
                    matchups['PvZ_wins'] += 1
            if match.winner_race == 'T':
                if match.loser_race == 'T':
                    matchups['TvT_games'] += 1
                    matchups['TvT_wins'] += 1
                if match.loser_race == 'P':
                    matchups['TvP_games'] += 1
                    matchups['TvP_wins'] += 1
                if match.loser_race == 'Z':
                    matchups['TvZ_games'] += 1
                    matchups['TvZ_wins'] += 1

        for match in losses:
            if match.loser_race == 'Z':
                if match.winner_race == 'T':
                    matchups['ZvT_games'] += 1
                if match.winner_race == 'P':
                    matchups['ZvP_games'] += 1
                if match.winner_race == 'Z':
                    matchups['ZvZ_games'] += 1
            if match.loser_race == 'P':
                if match.winner_race == 'T':
                    matchups['PvT_games'] += 1
                if match.winner_race == 'P':
                    matchups['PvP_games'] += 1
                if match.winner_race == 'Z':
                    matchups['PvZ_games'] += 1
            if match.loser_race == 'T':
                if match.winner_race == 'T':
                    matchups['TvT_games'] += 1
                if match.winner_race == 'P':
                    matchups['TvP_games'] += 1
                if match.winner_race == 'Z':
                    matchups['TvZ_games'] += 1

        return {
            'ZvT': "{0:.0f}%".format(matchups['ZvT_wins'] / matchups['ZvT_games'] * 100) if matchups['ZvT_games'] > 0 else "",
            'ZvP': "{0:.0f}%".format(matchups['ZvP_wins'] / matchups['ZvP_games'] * 100) if matchups['ZvP_games'] > 0 else "",
            'ZvZ': "{0:.0f}%".format(matchups['ZvZ_wins'] / matchups['ZvZ_games'] * 100) if matchups['ZvZ_games'] > 0 else "",
            'TvT': "{0:.0f}%".format(matchups['TvT_wins'] / matchups['TvT_games'] * 100) if matchups['TvT_games'] > 0 else "",
            'TvP': "{0:.0f}%".format(matchups['TvP_wins'] / matchups['TvP_games'] * 100) if matchups['TvP_games'] > 0 else "",
            'TvZ': "{0:.0f}%".format(matchups['TvZ_wins'] / matchups['TvZ_games'] * 100) if matchups['TvZ_games'] > 0 else "",
            'PvT': "{0:.0f}%".format(matchups['PvT_wins'] / matchups['PvT_games'] * 100) if matchups['PvT_games'] > 0 else "",
            'PvP': "{0:.0f}%".format(matchups['PvP_wins'] / matchups['PvP_games'] * 100) if matchups['PvP_games'] > 0 else "",
            'PvZ': "{0:.0f}%".format(matchups['PvZ_wins'] / matchups['PvZ_games'] * 100) if matchups['PvZ_games'] > 0 else "",
        }

    @property
    def unconfirmed_matches(self):
        unconfirmed_wins = Match.objects.filter(Q(winner=self) & Q(winner_confirmed=False)).count()
        unconfirmed_losses = Match.objects.filter(Q(loser=self) & Q(loser_confirmed=False)).count()
        return unconfirmed_wins + unconfirmed_losses

fbw/users/forms.py
from django import forms

from .models import User

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['battlenet', 'iccup', 'shield_battery', 'race']

    def clean_battlenet(self):
        return self.cleaned_data['battlenet'] or None

    def clean_iccup(self):
        return self.cleaned_data['iccup'] or None

    def clean_shield_battery(self):
        return self.cleaned_data['shield_battery'] or None

fbw/users/views.py
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User
from .forms import UserUpdateForm
from ladder.models import Match


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent_matches'] = Match.objects.filter(Q(winner=self.object) | Q(loser=self.object)).prefetch_related('winner', 'loser')[:5]
        return context

class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserUpdateForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

fbw/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

fbw/templates/base.html
{% load account socialaccount %}
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}fbw{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>

    {% get_providers as socialaccount_providers %}

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'ladder:index' %}">FBW Ladder</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'ladder:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'ladder:player-list' %}">{% trans "Rankings" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'ladder:match-list' %}">{% trans "Replays" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'tournaments' %}">{% trans "Tournaments" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'ladder:submit' %}"><button class="btn btn-primary" type="button">{% trans "Submit Replay" %}</button></a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_superuser %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="log-in-link" class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
                  </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'about' %}">{% trans "About" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            </ul>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'about' %}">{% trans "About" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% provider_login_url "discord" process="login" %}">{% trans "Sign In" %}</a>
              </li>
              </ul>
            {% endif %}
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% if request.user.is_authenticated %}
          {% if unconfirmed_matches %}
              <div class="alert alert-danger">You have <a href="{% url 'ladder:unconfirmed-matches' %}">{{ unconfirmed_matches }} unconfirmed match{{ unconfirmed_matches|pluralize:"es" }}</a>. Please confirm the results.</div>
          {% endif %}
            
          {% if no_profile %}
              <div class="alert alert-warning">You don't seem to have entered your iCCup or Battle.net handles to your profile. Please <a href="{% url 'users:update' %}">update your profile</a> as soon as possible.</div>
          {% endif %}

	  {% if request.user.is_superuser %}
		{% if outstanding_reports %}
		    <div class="alert alert-danger"><a href="{% url 'admin:ladder_report_changelist' %}">{{ outstanding_reports }} report{{ outstanding_reports|pluralize }}</a> is currently unresolved.</div>
		{% endif %}
	  {% endif %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 